server {
    listen 80;
    server_name 101.42.116.50 localhost;
    index index.html index.htm index.php;
    root /www/server/nginx/html;

    # 允许所有请求
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 错误日志
    access_log /www/wwwlogs/stock_access.log;
    error_log /www/wwwlogs/stock_error.log;
}
